spring:
  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=1,expireAfterAccess=3600s
bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      url: .*
      rate-limits:
        bandwidths:
          - capacity: 1
            time: 300
            unit: seconds