management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false
spring:
  cache:
    cache-names:
      - buckets
    caffeine:
      spec: maximumSize=1,expireAfterAccess=3600s
bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      url: .*
      rate-limits:
        - bandwidths:
            - capacity: 1
              time: 30
              unit: seconds
debug: true